language: java
jdk:
  - openjdk8
git:
  submodules: false

# Cache settings
cache:
  timeout: 600
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT  UPLOAD_BUILD=true
  - IDEA_VERSION=2019.2.4             UPLOAD_BUILD=false
  - IDEA_VERSION=2019.2               UPLOAD_BUILD=true

before_install:
  - chmod +x gradlew
  - pip install --user codecov

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33baacd26d1b840aebaa
    on_success: always
    on_failure: always
    on_start: never

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_KEY}"
  skip_cleanup: true
  file_glob: true
  file: "build/distributions/lombok-plugin-*.zip"
  on:
    tags: true
    condition: (( $TRAVIS_TAG =~ ^releasebuild_[0-9]+.*$ ) && ( $UPLOAD_BUILD=true ))
after_deploy:
  - ./gradlew publishPlugin
